version: '3.8'
services:
  confluence-cloud:
    build:
      context: .
      target: confluence-cloud
    image: onlyoffice/confluence-cloud:${PRODUCT_VERSION}
    container_name: onlyoffice-confluence-cloud
    depends_on:
      - postgresql
    environment:
      - NODE_ENV=${NODE_ENV}
      - AC_OPTS=${AC_OPTS}
      - PORT=${PORT}
      - AC_LOCAL_BASE_URL=${AC_LOCAL_BASE_URL}
      - DATABASE_URL=${DATABASE_URL}
    stdin_open: true
    restart: always
    ports:
      - '${PORT}:${PORT}'

  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    stdin_open: true
    restart: always
    expose:
      - '5432'

networks:
  default:
    name: onlyoffice
